### ISSUE TITLE
PRISMA-ScR Checklist (for both protocol and review itself)

### ISSUE THREAD

**Issue by lwjohnst86** [science-collective/scoping-review#14]
> Note: This checklist was generated with the script `R/extract-prisma-scr-checklist.R`.
The checklist can also be found at `doc/instructions/prisma-scr-checklist.md`.

**Title**:

- [ ] Title: Identify the report as a scoping review.

**Abstract**:

- [ ] Structured summary: Provide a structured summary that includes (as applicable): background, objectives, eligibility criteria, sources of evidence, charting methods, results, and conclusions that relate to the review questions and objectives.

**Introduction**:

- [ ] Rationale: Describe the rationale for the review in the context of what is already known. Explain why the review questions/objectives lend themselves to a scoping review approach.
- [ ] Objectives: Provide an explicit statement of the questions and objectives being addressed with reference to their key elements (e.g., population or participants, concepts, and context) or other relevant key elements used to conceptualize the review questions and/or objectives.

**Methods**:

- [ ] Protocol and registration: Indicate whether a review protocol exists; state if and where it can be accessed (e.g., a Web address); and if available, provide registration information, including the registration number.
- [ ] Eligibility criteria: Specify characteristics of the sources of evidence used as eligibility criteria (e.g., years considered, language, and publication status), and provide a rationale.
- [ ] Information sources*: Describe all information sources in the search (e.g., databases with dates of coverage and contact with authors to identify additional sources), as well as the date the most recent search was executed.
- [ ] Search: Present the full electronic search strategy for at least 1 database, including any limits used, such that it could be repeated.
- [ ] Selection of sources of evidence†: State the process for selecting sources of evidence (i.e., screening and eligibility) included in the scoping review.
- [ ] Data charting process‡: Describe the methods of charting data from the included sources of evidence (e.g., calibrated forms or forms that have been tested by the team before their use, and whether data charting was done independently or in duplicate) and any processes for obtaining and confirming data from investigators.
- [ ] Data items: List and define all variables for which data were sought and any assumptions and simplifications made.
- [ ] Critical appraisal of individual sources of evidence§: If done, provide a rationale for conducting a critical appraisal of included sources of evidence; describe the methods used and how this information was used in any data synthesis (if appropriate).
- [ ] Synthesis of results: Describe the methods of handling and summarizing the data that were charted.

**Results**:

- [ ] Selection of sources of evidence: Give numbers of sources of evidence screened, assessed for eligibility, and included in the review, with reasons for exclusions at each stage, ideally using a flow diagram.
- [ ] Characteristics of sources of evidence: For each source of evidence, present characteristics for which data were charted and provide the citations.
- [ ] Critical appraisal within sources of evidence: If done, present data on critical appraisal of included sources of evidence (see item 12).
- [ ] Results of individual sources of evidence: For each included source of evidence, present the relevant data that were charted that relate to the review questions and objectives.
- [ ] Synthesis of results: Summarize and/or present the charting results as they relate to the review questions and objectives.

**Discussion**:

- [ ] Summary of evidence: Summarize the main results (including an overview of concepts, themes, and types of evidence available), link to the review questions and objectives, and consider the relevance to key groups.
- [ ] Limitations: Discuss the limitations of the scoping review process.
- [ ] Conclusions: Provide a general interpretation of the results with respect to the review questions and objectives, as well as potential implications and/or next steps.

**Funding**:

- [ ] Funding: Describe sources of funding for the included sources of evidence, as well as sources of funding for the scoping review. Describe the role of the funders of the scoping review.
